[package]
name = "quiverdb-py"
version = "1.2.2"
edition = "2021"

[lib]
name = "quiverdb"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
pyo3 = { version = "0.26.0", features = ["extension-module"] }

# Ссылка на основной крейт:
quiverdb_core = { path = "../../", package = "QuiverDB" }